### ISSUE TITLE
Maybe remove the dependency on DataFrames?

### ISSUE THREAD

**Issue by yeesian** [penntaylor/DBaseReader.jl#1]
since it doesn't actually require functionality from DataFrames. DataArrays will likely be replaced with NullableArrays at some point (if you're interested, you can also see https://gist.github.com/johnmyleswhite/04f7b4fe3df76ea72f69). Maybe use a Dict of NullableArrays for now?

**Comment by penntaylor** [comment]
So instead of keeping records intact in a DataFrame or SubDataFrame when filtering, you'd instead do something like

```
indices = find(foo, records)
```

and then use the indices to index into any of the data columns or the shape array?

I played around with NullableArrays for a bit...is there some easier way to do anything with their contained values other than constantly wrapping everything in `get()` (or wrapping everything else in the world in `Nullable()`?

**Comment by yeesian** [comment]
Yeah, it does sound rather un-useful for now. I wrote utilities like https://github.com/yeesian/GeoConverters.jl to convert stuff to dataframes/compose-graphics/etc for that reason.

Although Shapefile doesn't return results in a DataFrame as well, the decision on removing dataframes isn't set in stone though. It's just that [it'll require a good argument](https://github.com/tedsteiner/OpenStreetMap.jl/issues/72#issuecomment-143056340) for having it in this package, versus having the user convert it themselves. If you're convinced that it should stay etc, I'd be okay with that too.

**Comment by penntaylor** [comment]
What about using a Dict of DataArrays for now? That would narrow the dependency down from the entirety of DataFrames to only DataArrays, would fit in with the indexing semantics of Shapefile, and would make an eventual transition to NullableArrays fairly straightforward.

**Comment by yeesian** [comment]
That sounds sensible :+1:
